### PR TITLE
feat(ch182): add support of ch182 (IDFGH-13607)

### PR DESCRIPTION
**Pull request by SergeyKharenko**
CH182 is an Ethernet PHY developed by NanjingQinhengMicroelectronics CO LTD (abbreviated as WCH). Interestingly, it is also integrated into the Ethernet MAC controller CH390, which can be inferred from Chapter 7 of the datasheet.
image
Therefore, this work is generally based on the phy part of CH390 #23 , and the following things are also done：
1. **MII/RMII mode switch or selection.** CH182 is setup MII mode after reset, so the driver will automatically setup RMII mode when the chip is being initialized.
2. **REF_CLK I/O mode selection.** ESP32 supports both REF_CLK input and output, and most of the examples are configured as input by default. This driver uses a compatible api paradigm to configure the mode by default, and also extends the api to give the user the option of using CLK Output mode.
3. **LED, START!!!** The LEDs on the RJ45 connector can convey a lot of information. This driver also provides relevant interfaces for configuration(for example, indicate network activity).
4. **Fix previous issues.** Correct memory distribution of vendor spec regs which is the opposite of the actual due to negligence. Change loopback mode from PMA loopback to remote loopback, which makes the loopback test pass(If possible, the CH390 driver should also make the above changes).

Performance benchmark using iperf is shown in the below table:
|CPU Frequency(MHz)|TX(Mbps)|RX(Mbps)|
|:-------------------------------:|:--------------:|:--------------:|
| 80|26|17.5|
|160|49|32.9|
|240|61.6|40|

Not bad~ Especially when the CPU runs at 240 MHz, the performance booms!

### This driver has also passed all of the tests in  `esp_eth\test_apps`. 

PS:
Here is the introduction to this ethernet controller in detail(translated from its official website):
_CH182 is an industrial grade 10/100M Ethernet PHY transceiver with Auto-MDIX support. CH182 internally includes Physical Coding Sublayer (PCS), Physical Media Access Layer (PMA), Twisted Pair Physical Medium Dependent (TP-PMD), 10BASE-TX encoder/decoder, Twisted Pair Media Attachment Unit (TPMAU), MII and RMII interfaces, and other modules required for Ethernet Transceiver functions.
The following figure shows the block diagram of CH182._
image

### CODE REVIEW

**Comment by kostaond** [comment]
@SergeyKharenko thank you for the PR. However, as I already mentioned somewhere else. Once we accept the new driver, we are taking the responsibility for the support. It means designing test board, maintain the code base and reported issues. Therefore we must be "picky" because such activities are expensive. By being "picky" I mean that the new chip needs to be special and promising in some of its parameters. For example, CH390 is super cheap, LAN867x supports new 10BASE-T1S standard, etc.

CH182 looks like generic PHY complying with IEEE802.3. Such cases are planned to be address with a new `Generic PHY` driver (see discussion [here](https://github.com/espressif/esp-eth-drivers/pull/28#issuecomment-2082923886)). The `Generic PHY` driver is already in review. For all these reasons I need to reject the PR. I hope you understand. 

However, feel free to maintain it under your personal repository. You can still distribute it over [ESP Component Registry](https://components.espressif.com/). I can help you with review. For example, I have some doubts regarding functionality of `ch182_set_rmii_refclk_dir`. I'm afraid it will not work when you would like to set PHY as source of REF_CLK programatically. Since if there is not REF_CLK at ESP32 input, the EMAC is not functional and so the SMI interface is not functional. Therefore, you never be able to set the PHY as REF_CLK source.

**Comment by SergeyKharenko** [comment]
@kostaond I fully understand and will continue to submit them to my registry in the future! Thank you very much for your valuable advice!

However, as mentioned earlier, there are errors in the CH390 driver that need to be corrected:

1.  In `esp_eth_phy_ch390.c` , memory distribution of the struct `phy_ctl1_reg_t` is actually in the order of big-endian mode, but ESP32 works in low-endian mode, which should be reversed. In fact, the best way is automatically determining the memory distribution of the struct according to `BYTE_ORDER` in `<machine/endian.h>`
2. In the function `ch390_loopback`:
```c
    if (enable) {
        bmcr.en_loopback = 1;
        phy_ctl1.pma_lpbk = 1;
    } else {
        bmcr.en_loopback = 0;
        phy_ctl1.pma_lpbk = 0;
    }
```
`pma_lpbk` should be changed to `remote_lpbk`. Otherwise, the test cannot be passed.

3. warning comment above `CH390_INFO_OUI` should be removed, because WCH has corrected the error in the new datasheet.

```c
/**
 * @warning This value is NOT the same as the datasheet!!! Hoping WCH fix it
 * in the furture version!
*/
#define CH390_INFO_OUI                       0x1CDC64
```
image

4. typo in `ch390.h`. Misspelling of Software
```c
#define NCR_RST         (1<<0) // Softwate reset
```
I sincerely hope that these suggestions will be adopted!

**Comment by kostaond** [comment]
@SergeyKharenko CH390 can be maintained at this repo.  As I mentioned, CH390 is interesting for us by its price. If there are any issues in CH390 driver, just create a pull request, please. Your suggestions will be certainly adopted. It's your baby and you're the expert here!

Regarding CH182, once you create your repo, you can include me as reviewer.

**Comment by SergeyKharenko** [comment]
@kostaond No problem! This PR and the CH395＇s could be closed! And I will submit a new PR for CH390 later. Thanks again for your patient😊😊😊

**Comment by kostaond** [comment]
Closed as per previous discussion. @SergeyKharenko will maintain the components under their own repo.

@SergeyKharenko thank you for your dedicated work! If you needed help with review in your own repo, just mark me as reviewer.

**Comment by SergeyKharenko** [comment]
@kostaond I have invited you to my repository! Your question has been answered in the README of CH182~

**Comment by kostaond** [comment]
@SergeyKharenko, thank you for the invitation. However, your repository is fork of this `esp-eth-drivers` repo. I'm not sure if it's optimal approach. I would rather recommend you to create completely new repository for your drivers. Otherwise it would make thing little bit messy sooner or later. 
I also noticed that you uploaded your own version of Ethernet init component. It's basically 1:1 copy to ours. It's not an issue in general but again can cause unnecessary confusion for end users. What about you create your own repo with your drivers, then publish them via Component Registry and we make dependency to them in our Ethernet Init? I just need to discuss internally.

**Comment by SergeyKharenko** [comment]
@kostaond My bad~ To be honest I  did not  think too much. Ethernet Init under my namespace will be taken down as soon as possible

**Comment by kostaond** [comment]
> @kostaond My bad~ To be honest I did not think too much. Ethernet Init under my namespace need to be taken down as soon as possible. But how to delete it ? I cannot find a guide.

No problem. I discussed with my colleagues. They say you can keep it as is! :) There is only one followup task for me to as outcome of the discussion. I need to investigate if there are any options how to easily extend `Ethernet Init` component with user's drivers in the future.

**Pull request closed without merging**
