### PR TITLE
add ETH PHY JL1101 (IDFGH-12581)

### PR DESCRIPTION
**Pull request by Jason2866**
follow up of https://github.com/espressif/esp-idf/pull/13572#issuecomment-2046332170

### CODE REVIEW

**Comment by kostaond** [comment]
@Jason2866 is there any board available with this chip so we could run some tests?

**Comment by Jason2866** [comment]
@kostaond Tested and used with this board https://templates.blakadder.com/dingtian_DT-R008.html

**Comment by kostaond** [comment]
@Jason2866 thank you very much for your effort! I briefly checked the history of the need of JL1101 driver on the internet (at Tasmota repo). If I understand it correctly, JL1101 has been used as replacement of LAN8720 by Dingtian. Am I right? On the other hand, the driver of JL1101 is based on RTL8201 (it's almost 1 to 1 copy). Have you tested all the features including loopback (its implementation often differs among vendors)? The point is, once we accept a driver to our repository, we need to maintain it and test if all driver's advertised features are fully functional. You can imagine it's not simple nor cheap (requires HW and test resources).

At this point I'm not sure if most of the users really want/need all the features fully functional based on the history of this particular driver and my discussions with other users. Most people are focused on basic PHY functionality (link up/down indication and functional Tx/Rx of course). Therefore, I've been thinking about creating a "generic" PHY driver which would support the basic features of Ethernet PHY's (basic features and interface is standardized under IEEE802.3). The generic driver would be distributed with a warning that some features functionality might be limited if vendor does not fully follow IEEE802.3. I believe it could cover most of the user's needs out of the box without creating a new driver. Would such approach make sense to you? The only thing I'm concerned about right now is speed/duplex indication since it also differs among vendors. I need to think if I'm able to find reliable solution.

As a conclusion, I'm probably not going to accept this PR in any near future. If you really want to make JL1101 driver available to public via Component Registry right now, you are free to do so under your private `namespace` and repository. Thank you for understanding and your feedback is very welcomed.

**Comment by TD-er** [comment]
I also have it running using ESPEasy on the same Dingtian node here, so I can also do some tests.

What do you need to know or tested?

- connect/disconnect
- 10M/100M speed
- ???

Currently my board is connected to an unmanaged 2.5G/10G switch, but I can also connect it via a managed switch so I can toggle the link speed.

**Comment by Jason2866** [comment]
> Therefore, I've been thinking about creating a "generic" PHY driver which would support the basic features of Ethernet PHY's (basic features and interface is standardized under IEEE802.3). The generic driver would be distributed with a warning that some features functionality might be limited if vendor does not fully follow IEEE802.3. I believe it could cover most of the user's needs out of the box without creating a new driver. Would such approach make sense to you? The only thing I'm concerned about right now is speed/duplex indication since it also differs among vendors. I need to think if I'm able to find reliable solution.

This sounds interesting. Since maintaining our own fork (which includes the driver) it is fine for me to close this PR.

**Comment by kostaond** [comment]
@TD-er if you are interested in the matter, you can add the driver to https://github.com/espressif/esp-idf/blob/master/components/esp_eth/test_apps/main/esp_eth_test_common.c, build, flash and run "ethernet" tests.

**Comment by kostaond** [comment]
The `Generic` PHY driver is currently in internal review and will be released soon. Therefore, I'm closing the issue. Thank you for the PR anyway.

**Comment by Jason2866** [comment]
Thats great news! Seeing forward to the generic PHY driver.
Thx for the great job you and your colleagues do!

**Comment by kostaond** [comment]
@Jason2866 the "Generic PHY" update has been finally synced with GH repo - https://github.com/espressif/esp-idf/commit/0738314308ad36a73601ddb8bb82f1dcbfe1f550. I would be grateful if you tested with your board to see if it fulfills its job.

**Comment by Jason2866** [comment]
@kostaond tested with the P4 devboard. Works with the PHY generic driver!

**Comment by kostaond** [comment]
@Jason2866 thank you for testing! I really appreciate your effort!

**Pull request closed without merging**
